# Model Params
use_default_params: True

params:
  model: "RandomForestRegressor"
  RFECV: False
  feature_select: True
  min_feature: 10
  best_params:
    n_estimators: 1200
    min_samples_split: 2
    min_samples_leaf: 4
    max_features: "auto"
    max_depth: 100
    bootstrap: True

default_params:
  model: "RandomForestRegressor"
  

# Data Params
DIR_RAW: "data/raw"
DIR_CLEAN: "data/clean"
data_path: "data/raw/AB_NYC_2019.csv"
data_set: "dgomonov/new-york-city-airbnb-open-data"
test_size: 0.2
columns_to_skew:
  - "price"

download_data_set: False
run_pipeline: True